### ISSUE TITLE
Nested parallel fails with loky backend on Python 3.9 only

### ISSUE THREAD

**Issue by glivan** [joblib/joblib#1247]
Hello,
I am encountering the following issue:

A two-level nested parallelization behaves as expected on Python 3.7 but fails or hangs (after finishing the computation correctly) on Python 3.9, when the loky backend is given as argument to Parallel. The issue is not present when no backend is specified. The issue is also present with two nested context managers are used to provide the backend information.

I expect the loky backend to be the default backend so I am surprised there is a difference between specifying a loky backend and not specifying a backend.

### Environment
Tests are performed on Debian10 in two different virtual environments:
env39: Python3.9 brand new environment created in virtualenv, with joblib-1.1.0 installed from pip install
env37: Python3.7 brand new environment created in virtualenv, with joblib-1.1.0 installed from pip install

Consider the following scripts, that should all perform the same thing:
**Script1**
```
from joblib import Parallel, delayed


def g(y):
    return y + 1


def f(x):
    res = Parallel(n_jobs=2)(delayed(g)(y) for y in [1, 2, 3, 4])
    return sum(res)


results = Parallel(n_jobs=4)(delayed(f)(x) for x in [1, 2, 3, 4])

print(results)
assert results == [14, 14, 14, 14]
```

**Script2**
```
from joblib import Parallel, delayed


def g(y):
    return y + 1


def f(x):
    res = Parallel(n_jobs=2, backend="loky")(delayed(g)(y) for y in [1, 2, 3, 4])
    return sum(res)


results = Parallel(n_jobs=4, backend="loky")(delayed(f)(x) for x in [1, 2, 3, 4])

print(results)
assert results == [14, 14, 14, 14]
```

**Script3**
```
from joblib import Parallel, delayed, parallel_backend


def g(y):
    return y + 1


with parallel_backend("loky"):

    def f(x):
        res = Parallel(n_jobs=2)(delayed(g)(y) for y in [1, 2, 3, 4])
        return sum(res)

    results = Parallel(n_jobs=4)(delayed(f)(x) for x in [1, 2, 3, 4])

print(results)
assert results == [14, 14, 14, 14]

```

**Script4**
```
from joblib import Parallel, delayed, parallel_backend


def g(y):
    return y + 1


def f(x):
    with parallel_backend("loky"):
        res = Parallel(n_jobs=2)(delayed(g)(y) for y in [1, 2, 3, 4])
    return sum(res)


with parallel_backend("loky"):
    results = Parallel(n_jobs=4)(delayed(f)(x) for x in [1, 2, 3, 4])

print(results)
assert results == [14, 14, 14, 14]
```

###  Expected results:
All scripts should print [14, 14, 14, 14] and terminate.

### Obtained results:

In env37: all scripts behave as expected.

In env39: Script1 and Script3 behave as expected.
Script2 and Script4 both print the expected result [14,14,14,14], then either 
- hang until a 5min timeout
- return an error message displayed below (eventually for different processes)
```
--------------------------------------------------------------------------------
LokyProcess-3:2 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/envs/env39/lib/python3.9/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/user/envs/env39/lib/python3.9/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------


--------------------------------------------------------------------------------
LokyProcess-2:1 failed with traceback: 
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/envs/env39/lib/python3.9/site-packages/joblib/externals/loky/backend/popen_loky_posix.py", line 199, in <module>
    process_obj = pickle.load(from_parent)
  File "/home/user/envs/env39/lib/python3.9/site-packages/joblib/externals/loky/backend/synchronize.py", line 122, in __setstate__
    self._semlock = _SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory


--------------------------------------------------------------------------------
```

**Comment by nishnik** [comment]
Same things happening to me.

Is there a resolution?

**Comment by jjerphan** [comment]
Hi, I cannot reproduce this issue with python 3.9.

<details>
<summary>Environment</summary>

```
# packages in environment at /home/jjerphan/.local/share/miniconda3/envs/joblib:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
ipython                   8.10.0             pyh41d4057_0    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.0.8                h0b41bf4_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       23.0               pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
python                    3.9.16          h2782a2a_0_cpython    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
setuptools                67.3.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
```

</details>

**Comment by cgr71ii** [comment]
Same problem here. Not use if is because of the python version, but my version is 3.10.6.

**Comment by lesteve** [comment]
What is your joblib and loky version?

The error message seems quite  similar to https://github.com/joblib/loky/issues/241, which has been fixed in 2.7.0 and thus should be fixed in joblib 1.2 which vendors loky 3.3.0.

**Comment by cgr71ii** [comment]
Well, in my case I have `joblib==1.2.0`, but I haven't installed `loky` nor I see it when I type `pip list`. I tried `python -c 'from loky import get_reusable_executor'` (example from https://github.com/joblib/loky), but I got `ModuleNotFoundError: No module named 'loky'`. I also tried python 3.8.5, but the problem persists.

My code, in case is useful for debugging, is:

```python
import sys
import subprocess

import joblib

sys.stdin.reconfigure(encoding='utf-8', errors="backslashreplace")

def get_http_code(url):
  cmd = subprocess.run(["curl", "-Is", url], capture_output=True)
  http_code = "NONE"
  return_code = cmd.returncode

  if return_code != 0:
#    sys.stderr.write(f"Rtn code != 0 in line #{idx} for URL '{url}': {return_code}\n")
    return return_code, http_code

  output = cmd.stdout.decode("utf-8", errors="backslashreplace").strip()

  if output:
    _output = output.split('\n')[0].split()

    if len(_output) >= 2:
      http_code = _output[1]

  return return_code, http_code

urls = []
lines = []
n_jobs = 1000

for idx, line in enumerate(sys.stdin, 1):
  line = line.rstrip('\n').split('\t')
  url = f"http://{line[0].rstrip('/')}/"

  urls.append(url)
  lines.append(line)

  if len(urls) >= n_jobs:
    asd = False
    while not asd:
      try:
        result = joblib.Parallel(n_jobs=n_jobs, max_nbytes=None)(joblib.delayed(get_http_code)(url) for url in urls)
        asd = True
      except Exception as e:
        sys.stderr.write(f"Exception: {e}\n")
        sys.stderr.flush()

    oks, http_codes = zip(*result)

    for ok, http_code, line in zip(oks, http_codes, lines):
      print('\t'.join(line) + f"\t{ok}\t{http_code}")

    sys.stdout.flush()

    lines = []
    urls = []
```

The program just gets the HTTP code of a list of authorities. I also attach the subset of URLs from the paracrawl project I'm using along with this script for debugging.

Execution:
```bash
zcat paracrawl-v9_en-is.tmx.gz.urls.uniq_domains_plus_tld.minus_mcc.gz | python3 check_http_code.py > urls.out 2> urls.err
```

[paracrawl-v9_en-is.tmx.gz.urls.uniq_domains_plus_tld.minus_mcc.gz](https://github.com/joblib/joblib/files/11092682/paracrawl-v9_en-is.tmx.gz.urls.uniq_domains_plus_tld.minus_mcc.gz)

**Comment by lesteve** [comment]
I am going to close this issue since the original issue has been fixed in joblib 1.2.0.

@cgr71ii I think your issue is not related. Quickly looking at your snippet, the main thing you want to try is to set `n_jobs` to something lower. `n_jobs=1000` does not make sense, unless you have a machine with 1000 cores which I kind of doubt. On top of doing `n_jobs=4` if you have 4 cores, you can also do `n_jobs=-1` to use all the cores on your machine, `n_jobs=-2` to use all the cores but 1, etc ...

If the error persists, please open a separate issue, if possible with a simpler snippet that reproduces.
